{"name": "Ошибка 401 при полученит списка заказов неавторизованным пользователем", "status": "passed", "description": "Проверка возвращения ошибки 401 Unauthorized при попытке получения cписка заказов неавторизованным пользователем", "steps": [{"name": "Создать заказ", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1716982788217, "stop": 1716982788650}, {"name": "Создать заказ", "status": "passed", "parameters": [{"name": "headers", "value": "None"}, {"name": "ingredients", "value": "{'ingredients': ['61c0c5a71d1f82001bdaaa6f', None, '61c0c5a71d1f82001bdaaa6d']}"}], "start": 1716982788652, "stop": 1716982789083}, {"name": "Получить все заказы конкретного пользователя", "status": "passed", "parameters": [{"name": "headers", "value": "None"}], "start": 1716982789085, "stop": 1716982789511}], "start": 1716982788217, "stop": 1716982789512, "uuid": "394ff03c-908f-48d5-b896-176e22809ef6", "historyId": "b8ce00a2e23dafe30a7ea86fb8398ea1", "testCaseId": "b8ce00a2e23dafe30a7ea86fb8398ea1", "fullName": "tests.test_get_users_orders.TestGetUsersOrders#test_get_order_list_not_auth_user_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_users_orders"}, {"name": "subSuite", "value": "TestGetUsersOrders"}, {"name": "host", "value": "LAPTOP-DIB55KQC"}, {"name": "thread", "value": "22508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_users_orders"}]}